### PR TITLE
Update About.cs

### PR DESCRIPTION
**Pull request by HatsuneMikuFan1**
No advertising paypal accounts.

### CODE REVIEW

**Comment by Lulalaby** [comment]
No

**Comment by davidcralph** [comment]
Nothing is being sold, therefore it meets the non-commercial usage policies of the Piapro character license.

**Comment by HatsuneMikuFan1** [comment]
Furthermore, you only need money if the project is a physical product. Last time I heard a discord bot isn’t a physical product.

**Comment by davidcralph** [comment]
GitHub projects are only the source code. The PayPal money goes towards paying the hosting fees for hosting the bot itself on Discord.

**Comment by Lulalaby** [comment]
> Furthermore, you only need money if the project is a physical product. Last time I heard a discord bot isn’t a physical product.

Could you just stfu? thx!

Seems like you don't know how many hours of code are in this bot.

**Comment by HatsuneMikuFan1** [comment]
Says the woman who said she identifies as a cat sometimes 💀

**Comment by Sekoree** [comment]
Hosting indeed costs me money, I don't think I have gotten anything, at least from the PayPal link but yea.
Also, I'm not using the bot to advertise my PayPal, it's in a credits command and not displayed on everything, if I was thirsty for money, I wouldn't try to get it through a discord bot lol

**Pull request closed without merging**
